// order
export const SET_SELECTED_ORDERS = "SET_ORDERS";
export const SET_ORDERS_OFFSET = "SET_ORDERS_OFFSET";
export const SET_ORDERS_LIMIT = "SET_ORDERS_LIMIT";
export const SET_ORDERS_SORT_BY = "SET_ORDERS_SORT_BY";
export const SET_ORDERS_DESC = "SET_ORDERS_DESC";
